# Generated by Django 2.0 on 2018-01-19 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pspuser',
            name='is_seller',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='pspuser',
            name='date_of_birth',
            field=models.DateField(help_text='Format YYYY-MM-DD'),
        ),
    ]
