# Generated by Django 2.0 on 2018-01-19 04:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_receiveableaccount'),
    ]

    operations = [
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('asset', models.CharField(choices=[
                 ('GAS', 'GAS'), ('NEO', 'NEO'), ('NEX', 'NEX')], default='GAS', max_length=3)),
                ('amount', models.FloatField(default=1.0)),
                ('sender_account_id', models.CharField(max_length=128)),
                ('receiver_account_id', models.CharField(max_length=128)),
                ('neo_address', models.CharField(max_length=34)),
                ('gas_price', models.FloatField()),
                ('fee', models.FloatField(default=0.05)),
                ('total_gas', models.FloatField()),
                ('total_fee', models.FloatField()),
                ('total', models.FloatField()),
                ('status', models.CharField(choices=[('STARTED', 'STARTED'), ('SUBMITTED', 'SUBMITTED'), (
                    'CONFIRMED', 'CONFIRMED')], default='STARTED', max_length=32)),
                ('user', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
