# Generated by Django 2.0 on 2018-01-19 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0004_purchase'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='transfer_id',
            field=models.CharField(default='stahoeusth', max_length=128),
            preserve_default=False,
        ),
    ]
