# Generated by Django 2.0 on 2018-01-19 04:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0005_purchase_transfer_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2018, 1, 19, 4, 28, 38, 411462)),
            preserve_default=False,
        ),
    ]
