# Generated by Django 2.0 on 2018-01-19 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0006_purchase_date_created'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchase',
            old_name='transfer_id',
            new_name='transfer_url',
        ),
    ]
