# Generated by Django 2.0 on 2018-01-19 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0007_auto_20180119_1434'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='failure_reason',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('processed', 'processed'), (
                'failed', 'failed')], default='pending', max_length=32),
        ),
    ]
