# Generated by Django 2.0 on 2018-01-19 16:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blockchain', '0001_initial'),
        ('customer', '0008_auto_20180119_1449'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='blockchain_transfer',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blockchain.BlockchainTransfer'),
        ),
    ]
