# Generated by Django 2.0 on 2018-01-19 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0009_purchase_blockchain_transfer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('processed', 'processed'), (
                'failed', 'failed'), ('complete', 'complete')], default='pending', max_length=32),
        ),
    ]
