# Generated by Django 2.0 on 2018-01-20 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0010_auto_20180119_1749'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='purchase',
            options={'ordering': ['-date_created']},
        ),
        migrations.AlterField(
            model_name='pspuser',
            name='date_of_birth',
            field=models.DateField(),
        ),
    ]
