# Generated by Django 2.0 on 2018-01-20 04:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blockchain', '0004_depositwallet_start_height'),
        ('customer', '0011_auto_20180120_0344'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deposit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset', models.CharField(choices=[('GAS', 'GAS'), ('NEO', 'NEO'), ('NEX', 'NEX')], default='GAS', max_length=3)),
                ('amount', models.FloatField(default=1.0)),
                ('sender_account_id', models.CharField(max_length=128)),
                ('receiver_account_id', models.CharField(max_length=128)),
                ('neo_address', models.CharField(max_length=34)),
                ('gas_price', models.FloatField()),
                ('fee', models.FloatField(default=0.05)),
                ('total_gas', models.FloatField()),
                ('total_fee', models.FloatField()),
                ('total', models.FloatField()),
                ('status', models.CharField(choices=[('pending', 'pending'), ('processed', 'processed'), ('failed', 'failed'), ('complete', 'complete')], default='pending', max_length=32)),
                ('transfer_url', models.CharField(max_length=128)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('failure_reason', models.CharField(blank=True, max_length=1024, null=True)),
                ('blockchain_transfer', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blockchain.BlockchainTransfer')),
                ('deposit_wallet', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='blockchain.DepositWallet')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_created'],
            },
        ),
    ]
