# Generated by Django 2.0 on 2018-01-20 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0012_deposit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deposit',
            name='neo_address',
        ),
        migrations.AddField(
            model_name='deposit',
            name='neo_sender_address',
            field=models.CharField(blank=True, max_length=34, null=True),
        ),
        migrations.AlterField(
            model_name='deposit',
            name='amount',
            field=models.FloatField(blank=True, default=1.0, null=True),
        ),
        migrations.AlterField(
            model_name='deposit',
            name='gas_price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='deposit',
            name='total',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='deposit',
            name='total_fee',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='deposit',
            name='total_gas',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='deposit',
            name='transfer_url',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
