# Generated by Django 2.0 on 2018-01-20 23:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0013_auto_20180120_2322'),
    ]

    operations = [
        migrations.AddField(
            model_name='pspuser',
            name='pending_deposit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='customer.Deposit'),
        ),
    ]
