# Generated by Django 2.0 on 2018-01-21 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0016_auto_20180121_1606'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deposit',
            name='asset',
            field=models.CharField(choices=[('GAS', 'GAS'), ('NEO', 'NEO'), ('NEX', 'NEX'), ('RPX', 'RPX')], default='GAS', max_length=3),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='asset',
            field=models.CharField(choices=[('GAS', 'GAS'), ('NEO', 'NEO'), ('NEX', 'NEX'), ('RPX', 'RPX')], default='GAS', max_length=3),
        ),
    ]
