# Generated by Django 2.0 on 2018-01-21 16:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0020_auto_20180121_1640'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pspuser',
            name='pending_deposit',
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='customer.Deposit'),
        ),
    ]
