# Generated by Django 2.0 on 2018-01-21 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0022_auto_20180121_1825'),
    ]

    operations = [
        migrations.AddField(
            model_name='deposit',
            name='date_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='purchase',
            name='date_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
