# Generated by Django 2.0 on 2018-01-27 18:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0023_auto_20180121_1912'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deposit',
            name='deposit_wallet',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='blockchain.DepositWallet'),
        ),
    ]
