# Generated by Django 2.0 on 2018-01-28 13:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0024_auto_20180127_1243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deposit',
            name='deposit_wallet',
            field=models.OneToOneField(
                default=1, on_delete=django.db.models.deletion.CASCADE, to='blockchain.DepositWallet'),
            preserve_default=False,
        ),
    ]
