# Generated by Django 2.0 on 2018-01-19 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blockchain', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blockchaintransfer',
            name='confirmed_block',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='blockchaintransfer',
            name='start_block',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
