# Generated by Django 2.0 on 2018-01-20 03:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blockchain', '0002_auto_20180119_1749'),
    ]

    operations = [
        migrations.CreateModel(
            name='DepositWallet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wallet_file', models.FilePathField()),
                ('wallet_pass', models.CharField(max_length=64)),
                ('depositor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='blockchaintransfer',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('processed', 'processed'), ('failed', 'failed'), ('complete', 'complete')], default='pending', max_length=64),
        ),
    ]
