# Generated by Django 2.0 on 2018-01-20 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blockchain', '0003_auto_20180120_0344'),
    ]

    operations = [
        migrations.AddField(
            model_name='depositwallet',
            name='start_height',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
