# Generated by Django 2.0 on 2018-01-21 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blockchain', '0005_auto_20180121_1606'),
    ]

    operations = [
        migrations.AlterField(
            model_name='price',
            name='asset',
            field=models.CharField(choices=[('GAS', 'GAS'), ('NEO', 'NEO'), ('NEX', 'NEX')], max_length=3, unique=True),
        ),
    ]
