# Generated by Django 2.0 on 2018-01-21 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blockchain', '0006_auto_20180121_1607'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blockchaintransfer',
            name='asset',
            field=models.CharField(choices=[('GAS', 'GAS'), ('NEO', 'NEO'), (
                'NEX', 'NEX'), ('RPX', 'RPX')], default='GAS', max_length=3),
        ),
        migrations.AlterField(
            model_name='price',
            name='asset',
            field=models.CharField(choices=[('GAS', 'GAS'), ('NEO', 'NEO'), (
                'NEX', 'NEX'), ('RPX', 'RPX')], max_length=3, unique=True),
        ),
        migrations.AlterField(
            model_name='price',
            name='usd',
            field=models.FloatField(default=0),
        ),
    ]
