# Generated by Django 2.0 on 2018-01-21 18:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blockchain', '0007_auto_20180121_1614'),
    ]

    operations = [
        migrations.AddField(
            model_name='depositwallet',
            name='transfer',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='blockchain.BlockchainTransfer'),
        ),
        migrations.AlterField(
            model_name='blockchaintransfer',
            name='status',
            field=models.CharField(choices=[('awaiting_deposit', 'awaiting_deposit'), ('gas_received', 'gas_received'), ('pending', 'pending'), ('processed', 'processed'), ('failed', 'failed'), ('complete', 'complete')], default='pending', max_length=64),
        ),
    ]
