# Generated by Django 2.0 on 2018-01-22 13:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blockchain', '0008_auto_20180121_1825'),
    ]

    operations = [
        migrations.AddField(
            model_name='depositwallet',
            name='transfer_to_main',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='main_transfer', to='blockchain.BlockchainTransfer'),
        ),
    ]
