"""
Django settings for nexpsp project.

Generated by 'django-admin startproject' using Django 2.0.

For more information on this file, see
https://docs.djangoproject.com/en/2.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.0/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'j3hvv3*s!fok!-ih9$e@+uv!eo9e964+0^u!)-v2*zk@u4^y9a'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']


DEFAULT_FROM_EMAIL = 'My Domain <noreply@mydomain.com>'

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',

    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.humanize',
    'localflavor',
    'customer',
    'bootstrap4',
    'blockchain.apps.BlockchainConfig',
]


MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'nexpsp.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': ['%s/templates' % BASE_DIR],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'nexpsp.context_processors.crypto_prices',
            ],
        },
    },
]

WSGI_APPLICATION = 'nexpsp.wsgi.application'


# Database
# https://docs.djangoproject.com/en/2.0/ref/settings/#databases

# Probably better to use postgres

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql_psycopg2',
        'NAME': 'psp',
    },
#    'default': {
#        'ENGINE': 'django.db.backends.sqlite3',
#        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
#    }
}


# Password validation
# https://docs.djangoproject.com/en/2.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


AUTHENTICATION_BACKENDS = (
    # Needed to login by username in Django admin, regardless of `allauth`
    'django.contrib.auth.backends.ModelBackend',

)

# Internationalization
# https://docs.djangoproject.com/en/2.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'America/Chicago'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.0/howto/static-files/

STATIC_URL = '/static/'

STATICFILES_DIRS = [
    os.path.join(BASE_DIR, "static"),
]


AUTH_USER_MODEL = 'customer.PSPUser'

LOGIN_URL = '/customer/login'
LOGIN_REDIRECT_URL = '/customer/purchase'
LOGOUT_REDIRECT_URL = '/'

EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'


# Neo related settings

NEOSCAN_URL = 'https://coz.neoscan-testnet.io/'

WALLET_DEPOSIT_PATH = '%s/Data/deposits' % BASE_DIR

CHAIN_DIR = "%s/Data/pspnet" % BASE_DIR

# loop settings ( all in seconds )
PERSIST_BLOCK_TIME = .1
WALLET_LOOP_TIME = .1
MONITOR_LOOP_TIME = 30
TRANSFER_LOOP_TIME = 2
CRYPTO_TRANSFER_LOOP_TIME = 3
PENDING_CRYPTO_TRANSFER_LOOP = 4
PENDING_GAS_TRANSFER_LOOP = 5
DWOLLA_TOKEN_REFRESH_TIME = 60 * 10
CMC_UPDATE_LOOP_TIME = 60 * 3
MOVE_DEPOSITS_LOOP_TIME = 60

# The following should probably be put is os.environ

PROTOCOL_FILE = 'protocol.coz.json'

PROVIDER_WALLET_FILE = 'new_myprovider.db3'
PROVIDER_WALLET_PASS = 'mypassword'

DWOLLA_KEY = 'AhsM66nKvorWWIwJL9WNCE3wO0FNIg0ajsB7v4lOQlUvnNGNyY'
DWOLLA_SECRET = 'o5863B3xHXYA60DQo1Gnsrl9zKKoOyGdOrayJTOQWNRm2a18Pd'
